version: 5.1.0
variant: default # cyberpunk
logo: # /images/logos/K4LM3D-text.png
  text: My Torn Diaries
head:
  favicon: /images/icons/favicon.ico
  manifest: # PWA
    name: Kalakal
    short_name: Kalakal
    start_url: https://kalmed.localplayer.dev # https://k4lm3d.github.io
    theme_color: '#91bf24'
    background_color: '#91bf24' # '#3273dc'
    display: standalone
    icons:
      -
        src: images/icons/apple-touch-icon.png
        sizes: 144x144
        type: image/png
      -
        src: images/icons/apple-touch-icon.png
        sizes: 152x152
      -
        src: images/icons/favicon.ico
        sizes: 72x72 96x96 128x128 256x256
  open_graph:
    title: Kalakal
    type: blog
    url: https://kalmed.localplayer.dev
    image: images/avatars/DALLE-K4LM3D.png
    site_name: Kalakal
    author: K4LM3D
    description: Torn Diaries
    twitter_card: 
    twitter_id: 
    twitter_site: 
    google_plus: 
    fb_admins: 
    fb_app_id: 
  structured_data:
    title: Kalakal
    description: Torn Diaries
    url: https://kalmed.localplayer.dev
    author: K4LM3D
    image: images/avatars/DALLE-K4LM3D.png
    publisher: K4LM3D
    publisher_logo: images/avatars/DALLE-K4LM3D-NOBG.png
  meta:
    - name=theme-color;content=#91bf24
    - name=generator;content="Hexo 4.2.0"
  rss: 
navbar:
  menu: 
    Home: /
    About: /about/
    Torn City: /Torn
  links:
    # Github:
    #   icon: fab fa-github
    #   url: https://github.com/K4LM3D
    # Facebook:
    #   icon: fab fa-facebook
    #   url: https://facebook.com/k4lm3dgg
    # Instagram:
    #   icon: fab fa-instagram
    #   url: https://www.instagram.com/k4lm3d
    # Twitter:
    #   icon: fab fa-twitter
    #   url: https://twitter.com/K4LM3D
    # TikTok:
    #   icon: fab fa-tiktok
    #   url: https://tiktok.com/K4LM3D
search:
  type: insight
  include_pages: false
  # Optional. Set to `false` to exclude pages from search results.
footer: 
  links:
    # About: /about
    Creative Commons:
      icon: fab fa-creative-commons
      url: 'https://creativecommons.org'
      'CC BY-NC-SA 4.0': ''
    Github:
      icon: fab fa-github
      url: https://github.com/K4LM3D
    Guilded:
      icon: fab fa-guilded
      url: https://guilded.gg/u/K4LM3D
    Itch:
      icon: fab fa-itch-io
      url: https://k4lm3d.itch.io/
    # Reddit:
    #   icon: fab fa-reddit
    #   url: https://www.reddit.com/user/K4LM3D
    # Twitch:
    #   icon: fab fa-twitch
    #   url: https://www.twitch.tv/k4lm3d_
  article:
    highlight:
      theme: atom-one-dark # xt256, qtcreator_dark, atom-one-light
      clipboard: true
      fold: unfolded
    readtime: true
    updated_time: false
    licenses:
      # Creative Commons:
      #   icon: fab fa-creative-commons
      #   url: 'https://creativecommons.org'
      # 'CC BY-NC-SA 4.0': ''
  # copyright: K4LM3D
sidebar:
  left:
    sticky: true
  right:
    sticky: false
widgets:
  -
    position: left
    type: profile
    author: Kalakal
    author_title: Civilian
    location: Torn City
    avatar: /images/banners/K4LM3D_standard.gif
    avatar_rounded: true
    # gravatar: 
    follow_link: # https://github.com/K4LM3D
    social_links:
      Facebook:
        icon: fab fa-facebook
        url: https://facebook.com/k4lm3dgg
      Instagram:
        icon: fab fa-instagram
        url: https://www.instagram.com/k4lm3d
      Twitter:
        icon: fab fa-twitter
        url: https://twitter.com/K4LM3D
      TikTok:
        icon: fab fa-tiktok
        url: https://tiktok.com/K4LM3D
  - 
    position: right
    type: toc
    index: true
  - position: right
    type: links
    links:
      Play Torn: https://www.torn.com
      Referral Link: https://www.torn.com/3091002
      My Bazaar: https://www.torn.com/bazaar.php?userId=3091002#/
plugins:
  animejs: true
  back_to_top: true
  # baidu_analytics:
  #   tracking_id: 
  # bing_webmaster:
  #   tracking_id: 
  # busuanzi: false
  # cnzz:
  #   id: 
  #   web_id: 
  gallery: true
  # google_analytics:
  #   tracking_id: 
  # hotjar:
  #   site_id: 
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
  # statcounter:
  #   project: 
  #   security: 
  # twitter_conversion_tracking:
  #   pixel_id: 
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
